language: ruby
rvm:
  - 2.2
  - jruby
  - truffleruby
  - 2.0.0-p247
  
before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    - LT_USERNAME=your username
    - LT_ACCESS_KEY=your access key
    
script:
  - bundle install
  - bundle exec rake single
